- name: Setup server 
  hosts: sonar_server
  become: true

  tasks:

    - name: update server
      apt:
        update_cache: yes
    
    - name: git install
      apt:
        name: git
        state: present

    - name: get the repo 
      git:
        repo: https://github.com/suryakant1811/MASTER-PROJECT.git
        dest: /opt/MASTER-PROJECT
        clone: yes
        update: yes


