- name: Install Jenkins
  hosts: sonar_server
  become: true

  tasks:

    - name: Install Java 17
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Fetch Jenkins GPG key from keyserver
      ansible.builtin.shell: |
        gpg --keyserver keyserver.ubuntu.com --recv-keys 7198F4B714ABFC68
        gpg --export 7198F4B714ABFC68 > /usr/share/keyrings/jenkins-keyring.gpg
        chmod 644 /usr/share/keyrings/jenkins-keyring.gpg
      args:
        creates: /usr/share/keyrings/jenkins-keyring.gpg

    - name: Add Jenkins repo
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/\n"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: true
















