- name: inatalling kubectl
  hosts: public
  become: true

  tasks:
    - name: download kubectl
      get_url: 
        url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
        dest: /tmp/kubectl

    - name: install kubectl
      copy:
        src: /tmp/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
        remote_src: yes