apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: backend-alert-config
  namespace: monitoring
  labels:
    release: monitoring

spec:
  route:
    receiver: "null"
    repeatInterval: 30m
    routes:
      - matchers:
          - name: alertname
            value: HighCpuUsage
        receiver: "send-email"

      - matchers:
          - name: alertname
            value: PodRestart
        receiver: "send-email"
        repeatInterval: 5m

  receivers:
    - name: "send-email"
      emailConfigs:
        - to: dummy181103@gmail.com
          from: dummy181103@gmail.com
          smarthost: smtp.gmail.com:587
          authUsername: dummy181103@gmail.com
          authIdentity: dummy181103@gmail.com
          sendResolved: false
          authPassword:
            name: mail-pass
            key: gmail-pass

    - name: "null"