apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: suryasuraj/server:44
          imagePullPolicy: Always

          ports:
            - containerPort: 7777

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MONGO_URI

          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"
